#!/bin/bash

LOG="/home/pi/pihole/etc-pihole/logs/pihole.log"
STATE="/tmp/pihole_log_last_pos"
BUCKET="s3://pi-logs-bucket-xxxxxxx/pihole"
DATE=$(date +%F)
TIME=$(date +%H%M)
OUTFILE="/tmp/pihole-${DATE}-${TIME}.log"

POS=$(cat "$STATE" 2>/dev/null || echo 0)
SIZE=$(stat -c%s "$LOG")

[ "$POS" -gt "$SIZE" ] && POS=0

if [ "$SIZE" -gt "$POS" ]; then
    dd if="$LOG" bs=1 skip="$POS" of="$OUTFILE" status=none
    aws s3 cp "$OUTFILE" "$BUCKET/$DATE/pihole-${DATE}-${TIME}.log"
    echo "$SIZE" > "$STATE"
    rm "$OUTFILE"
fi
